# -*- coding: utf-8 -*-
"""test_converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gamEkiwQP7ulz0_vzjPXfkFeKIaYD2kr
"""

import pytest
from converter import CurrencyConverter

def test_fetch_rates():
    converter = CurrencyConverter()
    success = converter.fetch_rates()
    assert success
    assert 'USD' in converter.rates or len(converter.rates) > 0